[preferred]
default=kde;gtk;gnome;wlr;
org.freedesktop.impl.portal.Secret=kwallet;
org.freedesktop.impl.portal.FileChooser=kde;
org.freedesktop.impl.portal.ScreenCast=gnome;
org.freedesktop.impl.portal.Screenshot=gnome;
