# gamma-correct-blending=true
lines=14
width=36
prompt = ""
minimal-lines = true
fields="filename,name,generic,exec,categories,keywords,comment"
line-height=18
inner-pad=4
horizontal-pad=12
vertical-pad=10

[border]
width=1
radius=0
# radius=4
# selection-radius=4

[colors]
background=303446ee
text=c6d0f5ff
prompt=b5bfe2ff
placeholder=838ba7ff
input=c6d0f5ff
match=e78284ff
selection=626880ff
selection-text=c6d0f5ff
selection-match=e78284ff
counter=838ba7ff
border=e78284ff

[key-bindings]
delete-line-forward = none
next = Down Shift+j
prev = Up Shift+k
next-page = Control+j
prev-page = Control+k
