[mgr]
show_hidden = true
ratio = [1, 2, 2]

[preview]
wrap = "yes"

[opener]
edit = [
  { run = "$EDITOR %s", block = true, for = "unix" },
	{ run = "%EDITOR% %s", block = true, for = "windows" },
] 
open = [
  { run = 'xdg-open %s', for = "linux" },
]

[open]
prepend_rules = [
  # { name = "*/", use = [
  #   "open",
  #   "reveal",
  #   "edit",
  # ] },
  { name = "*.toml", use = "edit" },
]
