[helpers]

[default]
depends = [
]

[default.files]
bottom = "~/.config/bottom"
direnv = "~/.config/direnv"
fish   = { target = "~/.config/fish", type = "symbolic", recurse = false }
gitui  = "~/.config/gitui"
helix  = "~/.config/helix"
yazi   = { target = "~/.config/yazi", type = "symbolic", recurse = false }
# guix   = { target = "~/.config/guix", type = "symbolic", recurse = false }


[desktop]
depends = [  ]
[desktop.files]
niri   = "~/.config/niri"
ghostty = "~/.config/ghostty"

[settings]
default_target_type = "automatic"
