[helpers]

[default]
depends = [
]

[default.files]
bottom = "~/.config/bottom"
direnv = "~/.config/direnv"
fish   = { target = "~/.config/fish", type = "symbolic", recurse = false }
gitui  = "~/.config/gitui"
helix  = "~/.config/helix"
yazi   = "~/.config/yazi"
home = "~"
home-manager = "~/.config/home-manager"
'.config' = { target = "~/.config", type = "symbolic" }
'scripts' = "~/scripts"

[desktop]
depends = [  ]
[desktop.files]
niri   = "~/.config/niri"
ghostty = "~/.config/ghostty"
fuzzel = "~/.config/fuzzel"

[settings]
default_target_type = "automatic"
