[helpers]

[default]
depends = [
]

[default.files]
fish  = { target = "~/.config/fish", type = "symbolic", recurse = false }
gitui = "~/.config/gitui"
helix = "~/.config/helix"
pwsh  = ""
yazi  = { target = "~/.config/yazi", type = "symbolic", recurse = false }

[settings]
default_target_type = "automatic"
